import { NavBar } from './components/Navbar/NavBar'
import 'src/app/styles/globals.scss'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="js">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
