import { NavBar } from './components/Navbar/NavBar'
import { Footer } from '@/app/components/Footer/Footer';

import 'src/app/styles/globals.scss'
import { Noto_Sans, Noto_Sans_JP } from 'next/font/google'

import FooterJson from '@/app/components/Footer/Footer.json'


const notojp = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-notojp",
  display: "swap",
});

const noto = Noto_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noto",
  display: "swap",
});



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja" className={`${noto.variable} ${notojp.variable}`}>
      <body>
        <div className="wrapper">
          <NavBar></NavBar>
          {children}
          <Footer FooterJson={FooterJson}></Footer>
        </div>
      </body>
    </html>
  )
}
